### ISSUE TITLE
Question concerning sports AI

### ISSUE THREAD

**Issue by mwpowellhtx** [martindevans/SharpSteer2#13]
Hello, I am interested to find out more about OpenSteer entree into the .NET realm, especially this SharpSteer.

I am interested to apply this in a sports genre, American Football to start with, likely headless (no, or at minimum crude, visualization, only "simulation" as it were, to start with). Unless needed, definitely no XNA. Do not need/want that as a dependency just now.

If I visualize anything it is likely to be using something like Unity 3D, but more like Helix Toolkit based approach. This is neither here nor there, but to say that if I can use OpenSteer to simulate those motions in a loosely coupled way, the it really shouldn't matter (in theory) which head I use.

I'll check it out, but also interested in some feedback along these lines. I am also encouraged by the fact that, although OS seems to be well beyond end of life, SS seems to be actively maintained, even though extremely niche.

Certainly something that helps to bridge between goals/instructions/skills of underlying AI actors into "tangible" behaviors is just what I want.

**Comment by mwpowellhtx** [comment]
i.e. Notes like "Modified to completely remove XNA dependency from the library" is just the sort of thing that would work with me.

**Comment by martindevans** [comment]
Hi Michael

SharpSteer ought to work fairly well for a sports simulation - it works
really well for primitive behaviours (path following, obstacle avoiding)
which can be used by higher level AI (some kind of tactical simulation of
the game and passing the ball etc). I use it in my own game as the the
basis of all AIs in the game, that's a co-operative multiplayer stealth
game with some shooting/combat elements - so as you can imagine the AI at a
high level is seriously complex - but it all builds on SS just fine :)

As you note in your second email, SS itself no longer depends on XNA. Only
the demo project currently depends on XNA.

If you have any specific questions related to SS feel free email me
or to open up issues on the SS repo :)

Martin

On 11 October 2015 at 18:48, Michael Powell notifications@github.com
wrote:

> i.e. Notes like "Modified to completely remove XNA dependency from the
> library" is just the sort of thing that would work with me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/martindevans/SharpSteer2/issues/13#issuecomment-147228004
> .

## 

http://martindevans.me

**Comment by mwpowellhtx** [comment]
Sounds great! No specific questions right at the moment. I'm certain when I approach a moment of intersection that I actually start adapting my modeling artifacts with SS, I will have a ton more questions. No promises, but as opportunities present themselves, also contribute to unit testing, which in turn I find helps increase the understanding as well.
